# Generated by Django 4.2.13 on 2024-06-15 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 15, 12, 18, 29, 973746)
            ),
        ),
    ]
